name: uztexsoftclients
description: "UztexSoft Clients Project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  file_picker: ^4.2.5
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.0
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  assets:
    - assets/images/scanner.png
    - assets/images/icon.png
  uses-material-design: true
